import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {config} from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Nav from "./(components)/Nav";

config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ticketing App",
  description: "Generated by SOC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="flex flex-col h-screen max-h-screen ">
            <Nav/>
            <div className="flex-grow overflow-y-auto bg-[var(--page)] text-[var(--default-text)]">{children}</div>
          </div>
      </body>
    </html>
  );
}
